name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # پوری گٹ ہسٹری ڈاؤنلوڈ کرنے کے لیے

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant permissions to Gradle files
        run: |
          chmod +x gradlew
          chmod +x gradle/wrapper/gradle-wrapper.jar

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Shoaib-Islamic-App
          path: app/build/outputs/apk/debug/app-debug.apk
